### PR TITLE
Next features and approvements

### PR DESCRIPTION
**Pull request by seehase**

### CODE REVIEW

**Comment by seehausen** [comment]
@ericplan give me 30min, I will remove [farm] section and display information from [plant]
I will push changes soon

**Comment by ericplan** [comment]
Hi,

Take your time,

I do some work at the background.

Eric

**Comment by seehausen** [comment]
@ericplan done

please check parameter, add/change description, make it nicer and more readable
- removed [farm]
- moved some parameters to general section
- Removed duplicate or non used display information
- support for commented lines starting (; / # <)
- multiline description useing "< br > " as newline

**Comment by ericplan** [comment]
Hi Holger,

First comment in a word doc. I thought it would be convenient, but now I’m not so sure. Overal impression is much better

BTW Does EMU = none mean that this items are not parsed? Otherwise you could skip this question and parse the items nonetheless 

Regards,￼

Eric

**Comment by seehase** [comment]
If general parameter
useEMU = false

I will not validate [EMU] section mean no warning. if it is true, I check that
path_CSV_data =
PVO_API =
PVO_SYS_ID =
are set

the hole file is parsed always. but some validations are skipped. same for Images, and WEEWX

We could add a bigger
###############################################################################
#   below this all is optional
###############################################################################

section in the parameter file
so
[images]
[weewx]
[EMU]

must not be present
(I would keep it as sample, but better separation is recommended

So we have
general, database and at least one plant mandatory



From: ericplan ***@***.***>
Date: Tuesday, 25. July 2023 at 21:25
To: seehase/ZonPHP ***@***.***>
Cc: seehase ***@***.***>, Author ***@***.***>
Subject: Re: [seehase/ZonPHP] Next features and approvements (PR #57)
Hi Holger,

First comment in a word doc. I thought it would be convenient, but now I’m not so sure. Overal impression is much better

BTW Does EMU = none mean that this items are not parsed? Otherwise you could skip this question and parse the items nonetheless

Regards,￼

Eric

**Comment by seehausen** [comment]
@ericplan 
what do you think about moving
useWeewx = false and useEMU = false
into the corresponding section and call it enabled = true/false (default false)

```
[weewx]
enabled = false
# Database host of your WEWWX database, can be different to the zonPHP database
host = localhost
```

so if it is false or the hole section is missing, we ignore it
so we will have less general parameters and for "advanced" user they can configure it in the "optional" sections

2.
are we sure that we need
```
# define display interval, default is 5 for solar log
# allowed:  1,2,3,4,5,6,10,12,15,20,30,60 sample  xls = 10, SolarLog = 5, SIC = 4
displayInterval = 5
```
or is it defined by the imported data? sunnyExplorer anyway imports in 5min interval
I will check if that is needed or working automatically

In best case we can remove
displayInterval = 5
coefficient = 1
installationDate  = 2023-07-14
useWeewx = false
useEMU = false

**Comment by ericplan** [comment]
Hi,

About Weewx and EMU, OK for me, and a nice simplification.

About display interval, I never really understood its meaning, but I know it is somewhere used in the day_chart sql. 

$sql = "SELECT SUM( Geg_Dag ) AS gem, naam, STR_TO_DATE( CONCAT( DATE( Datum_Dag ) , ' ',HOUR( Datum_Dag ) , ':', LPAD( FLOOR( MINUTE( Datum_Dag ) /" .
    $params['displayInterval'] . " ) *" . $params['displayInterval'] . ", 2, '0' ) , ':00' ) , '%Y-%m-%d %H:%i:%s' ) AS datumtijd " .
    " FROM " . TABLE_PREFIX . "_dag " .
    " WHERE Datum_Dag LIKE '" . date("Y-m-d", $chartdate) . "%' " .
 " GROUP BY datumtijd, naam “ . " ORDER BY datumtijd ASC”;

So we could set it to a default. To remove it we have to do some more actions, but I guess it is no problem to remove it as well.

Regards,

Eric

**Comment by ericplan** [comment]
Hi,

STR_TO_DATE( CONCAT( DATE( Datum_Dag ) , ' ',HOUR( Datum_Dag ) , ':', LPAD( FLOOR( MINUTE( Datum_Dag ) /5 ) *5, 2, '0' ) , ':00' ) , '%Y-%m-%d %H:%i:%s' ) AS datumtijd 

is just a difficult way to write 

Datum_Dag AS datumtijd

At least when we default it to 5.

Regards,

Eric

**Comment by seehase** [comment]
yes there are a lot of strange old code

omzetdatum($TimeStamp);//date("Y-m-d H:i:s",strtotime($TimeStamp));

omzetdatum is doing
date("Y-m-d H:i:s",strtotime($TimeStamp))
in a complex way

From: ericplan ***@***.***>
Date: Thursday, 27. July 2023 at 16:38
To: seehase/ZonPHP ***@***.***>
Cc: seehase ***@***.***>, Author ***@***.***>
Subject: Re: [seehase/ZonPHP] Next features and approvements (PR #57)
Hi,

STR_TO_DATE( CONCAT( DATE( Datum_Dag ) , ' ',HOUR( Datum_Dag ) , ':', LPAD( FLOOR( MINUTE( Datum_Dag ) /5 ) *5, 2, '0' ) , ':00' ) , '%Y-%m-%d %H:%i:%s' ) AS datumtijd

is just a difficult way to write

Datum_Dag AS datumtijd

At least when we default it to 5.

Regards,

Eric

**Pull request merged**
