### PR TITLE
Bug fix, December not showing in dropdown

### PR DESCRIPTION
**Pull request by ericplan**

### CODE REVIEW

**Review by seehausen — APPROVED** [review]
looks good...

**Comment by ericplan** [comment]
Hi,

First commit with the Sourcetree-app. But why is this push label not gowing away?


￼

**Comment by seehausen** [comment]
You can merge if you do not want to make additional changes in that fix

**Comment by ericplan** [comment]
Hi,

I guess I did it. I’m going to do a very small change on a language file, just to practice the whole process. I hope you don’t mind.

Eric

**Pull request merged**
